### ISSUE TITLE
Bug: Execution failed for task ':background_location:compileReleaseKotlin' ((Highest Priority Issue))

### ISSUE THREAD

**Issue by dipakravalVH** [Almoullim/background_location#243]
e: file:///Users/himanshujaiswal/.pub-cache/hosted/pub.dev/background_location-0.13.0/android/src/main/kotlin/com/almoullim/background_location/BackgroundLocationPlugin.kt:18:52 Unresolved reference 'Registrar'.
e: file:///Users/himanshujaiswal/.pub-cache/hosted/pub.dev/background_location-0.13.0/android/src/main/kotlin/com/almoullim/background_location/BackgroundLocationPlugin.kt:20:50 Unresolved reference 'context'.
e: file:///Users/himanshujaiswal/.pub-cache/hosted/pub.dev/background_location-0.13.0/android/src/main/kotlin/com/almoullim/background_location/BackgroundLocationPlugin.kt:20:71 Unresolved reference 'messenger'.
e: file:///Users/himanshujaiswal/.pub-cache/hosted/pub.dev/background_location-0.13.0/android/src/main/kotlin/com/almoullim/background_location/BackgroundLocationPlugin.kt:21:23 Unresolved reference 'addRequestPermissionsResultListener'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':background_location:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 5s

-------------------------------

I'm facing a issue while creating a appbundle, might be it is related to embedding version issue, please fix it asap, so every one can easily access the package,

Flutter 3.32.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fcf2c11572 (4 weeks ago) • 2025-06-24 11:44:07 -0700
Engine • revision dd93de6fb1 (4 weeks ago) • 2025-06-24 07:39:37 -0700
Tools • Dart 3.8.1 • DevTools 2.45.1

**Comment by dipakravalVH** [comment]
Merge the PR #240  that was given - it's fine. I used it and didn’t face any issues; even the app bundle was created successfully, Thanks!

**Comment by MoralCode** [comment]
> The service is also mentioned in the xml file, and the tracking notification is sticky as well, plus the navigation symbol is also showing, still, it's not working.

are you saying the codebase as-is with the fix from #240 still does not work in flutter 3.32.5?

**Comment by dipakravalVH** [comment]
Yes, that wasn’t working, even with the PR mentioned above of the other developer.
Still, I’ll need to check it again, but for now, I’ve implemented this feature in another way.
I’d suggest please try to keep this package and code updated so that features like this can be easily accessed on the Flutter platform, especially in such a competitive market.

**Comment by MoralCode** [comment]
> Yes, that wasn’t working, even with the PR mentioned above of the other developer.

Are you able to provide logs of the additional errors you saw to help support the maintenance efforts?

> especially in such a competitive market

This project has been essentially abandoned by its original creator and most of the maintenance is now done on an as-needed/reactive basis by volunteers. I'm not sure there's currently much interest in or need to stay competitive in a commercial marketplace.

If people value this package and want to use or contribute back to it, that's awesome, but my honest recommendation - especially if you are relying on this for the commercial success of a business or profit-making entity - would be to find a different package (such as one where a company is paying its employees to help maintain it). That is going to be a lot more stable for your business needs than this package that's being (arguably barely) held together by a loose band of volunteer strangers.

**Comment by proninyaroslav** [comment]
I encountered the same problem and applied #240, now the build runs without errors.
